export { default as UserIcon } from './Group.svg'
export { default as CartIcon } from './iconfinder_shopping-cart_2561279 1.svg'
export { default as PizzaIcon } from './icons8-пицца-96 1.svg'
export { default as PlusIcon } from './plus.svg'
export { default as SearchIcon } from './Vector.svg'
